# Generated by Django 2.2.16 on 2023-02-07 21:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_auto_20230202_2148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingСart',
            new_name='ShoppingCart',
        ),
    ]
